language: cpp
dist: xenial

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:beineri/opt-qt592-xenial'
    packages:
      - build-essential
      - g++-4.9
      - g++-8
      - clang-3.5
      - qt59base
      - tree

branches:
  only:
    - master

matrix:
  include:
    # g++ 4.9
    - os: linux
      compiler: gcc
      env: COMPILERS="CC=gcc-4.9 CXX=g++-4.9"
    # g++ 5.5
    - os: linux
      compiler: gcc
    # g++ 8
    - os: linux
      compiler: gcc
      env: COMPILERS="CC=gcc-8 CXX=g++-8"
    # clang 3.5
    - os: linux
      compiler: clang
      env: COMPILERS="CC=clang-3.5 CXX=clang++-3.5"
    # clang 7
    - os: linux
      compiler: clang

before_install:
  - chmod +x travis/*.sh
  - source travis/before_install.sh

before_script:
  - source travis/before_script.sh

script:
  - source travis/script.sh
