language: cpp
dist: xenial

branches:
  only:
    - master

matrix:
  include:
    # g++ 4.9
    # qt 5.9.2
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt592-xenial'
          packages:
            - build-essential
            - g++-4.9
            - qt59base
            - cppcheck
            - tree
      env:
        - COMPILERS="CC=gcc-4.9 CXX=g++-4.9"
        - QT="5.9"
    # g++ 4.9
    # qt 5.12
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
          packages:
            - build-essential
            - g++-4.9
            - qt512base
            - cppcheck
            - tree
      env:
        - COMPILERS="CC=gcc-4.9 CXX=g++-4.9"
        - QT="5.12"
    # g++ 5.4
    # qt 5.9.2
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt592-xenial'
          packages:
            - build-essential
            - qt59base
            - cppcheck
            - tree
      env:
        - QT="5.9"
    # g++ 5.4
    # qt 5.12
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
          packages:
            - build-essential
            - qt512base
            - cppcheck
            - tree
      env:
        - QT="5.12"
    # g++ 8
    # qt 5.9.2
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:beineri/opt-qt592-xenial'
          packages:
            - build-essential
            - g++-8
            - qt59base
            - cppcheck
            - tree
      env:
        - COMPILERS="CC=gcc-8 CXX=g++-8"
        - QT="5.9"
    # g++ 8
    # qt 5.12
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
          packages:
            - build-essential
            - g++-8
            - qt512base
            - cppcheck
            - tree
      env:
        - COMPILERS="CC=gcc-8 CXX=g++-8"
        - QT="5.12"
    # clang 3.5
    # qt 5.9.2
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt592-xenial'
          packages:
            - build-essential
            - clang-3.5
            - qt59base
            - cppcheck
            - tree
      env:
        - COMPILERS="CC=clang-3.5 CXX=clang++-3.5"
        - QT="5.9"
    # clang 3.5
    # qt 5.12
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
          packages:
            - build-essential
            - clang-3.5
            - qt512base
            - cppcheck
            - tree
      env:
        - COMPILERS="CC=clang-3.5 CXX=clang++-3.5"
        - QT="5.12"
    # clang 7
    # qt 5.9.2
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt592-xenial'
          packages:
            - build-essential
            - qt59base
            - cppcheck
            - tree
      env:
        - QT="5.9"
    # clang 7
    # qt 5.12
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
          packages:
            - build-essential
            - qt512base
            - cppcheck
            - tree
      env:
        - QT="5.12"

before_install:
  - chmod +x travis/*.sh
  - source travis/before_install.sh

before_script:
  - source travis/before_script.sh

script:
  - source travis/script.sh
