language: cpp
dist: xenial

matrix:
  include:
    - os: linux
      env: COMPILER=gcc
    - os: linux
      env: COMPILER=clang

branches:
  only:
    - master

before_install:
  - chmod +x travis/*.sh
  - source travis/before_install.sh

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7
      - sourceline: 'ppa:beineri/opt-qt592-xenial'
    packages:
      - build-essential
      - gcc-8
      - g++-8
      - clang-7
      - qt59base
      - tree

script:
  - source travis/script.sh
