language: cpp
sudo: required

services:
  - docker

branches:
  only:
    - master

compiler:
  - gcc
  - clang

arch:
  packages:
    - qt5-base
    - qt5-tools
  script:
    - travis/build.sh
    - travis/run.sh

script:
  - curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash
