language: cpp
dist: xenial

matrix:
  include:
    - os: linux
      env: COMPILERS="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      env: COMPILERS="CC=gcc-8 && CXX=g++-8"
    - os: linux
      env: COMPILERS="CC=clang-3.5 && CXX=clang++-3.5"
    - os: linux
      env: COMPILERS="CC=clang-7 && CXX=clang++-7"

branches:
  only:
    - master

before_install:
  - eval "${COMPILERS}"
  - chmod +x travis/*.sh
  - source travis/before_install.sh

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7
      - sourceline: 'ppa:beineri/opt-qt592-xenial'
    packages:
      - build-essential
      - g++-4.9
      - g++-8
      - clang-3.5
      - clang-7
      - qt59base
      - tree

before_script:
  - source travis/before_script.sh

script:
  - source travis/script.sh
