name: GitHub Actions CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Qt ${{ matrix.qt-version }}, ${{ matrix.compiler-type }}
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        qt-version: [5.9, 5.12]
        compiler-type: [gcc, clang]
    steps:
      - name: Checkout sources
        uses: actions/checkout@master
      - name: Install common packages
        run: sudo apt install build-essential cppcheck tree
      - name: Setup Qt ${{ matrix.qt-version }}
        env:
          QT_VER: ${{ matrix.qt-version }}
        run: |
          if [[ $QT_VER == "5.9" ]]
          then
            sudo add-apt-repository "ppa:beineri/opt-qt592-$(lsb_release -cs)"
            sudo apt update
            sudo apt install qt59base
          elif [[ $QT_VER == "5.12" ]]
          then
            sudo add-apt-repository "ppa:beineri/opt-qt-5.12.10-$(lsb_release -cs)"
            sudo apt update
            sudo apt install qt512base
          fi
          echo "QTDIR=/opt/qt${QT_VER//./}" >> $GITHUB_ENV
          echo "/opt/qt${QT_VER//./}/bin" >> $GITHUB_PATH
          if [[ $(uname -m) == "x86_64" ]]
          then
            echo "/opt/qt${QT_VER//./}/lib/x86_64-linux-gnu" >> $GITHUB_PATH
            echo "/opt/qt${QT_VER//./}/lib" >> $GITHUB_PATH
          else
            echo "/opt/qt${QT_VER//./}/lib/i386-linux-gnu" >> $GITHUB_PATH
            echo "/opt/qt${QT_VER//./}/lib" >> $GITHUB_PATH
          fi
          echo "/opt/qt${QT_VER//./}/lib/pkgconfig" >> $GITHUB_PATH
      - name: Run Cppcheck
        run: cppcheck --enable=all --inconclusive --report-progress --std=c++11 src/
      - name: Build package
        run: |
          mkdir build
          cd build
          qmake ../ CONFIG+=release CONFIG+=pkgconfig
          make
          make INSTALL_ROOT=pkg install
          make distclean
          tree -p pkg/
          qmake ../tests/
          make
          make check
          make distclean
