name: CI

on:
  push:
    branches: [master]
  pull_request: {}

jobs:
  build:
    name: Qt ${{ matrix.qt-version }}, ${{ matrix.compiler-type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        qt-version: ['5.9.2', '5.15.0', '6.2.0']
        compiler-type: [gcc, clang]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install common packages
        run: sudo apt install build-essential cppcheck tree p7zip

      - name: Setup compiler
        env:
          COMP_TYPE: ${{ matrix.compiler-type }}
        run: |
          if [[ "${COMP_TYPE}" == "clang" ]]
          then
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          else
            echo "CC=gcc" >> $GITHUB_ENV
            echo "CXX=g++" >> $GITHUB_ENV
          fi

      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt-version }}
          host: linux
          target: desktop
          install-deps: false
          archives: icu qtbase
          cache: true
          setup-python: false
          extra: --external 7z

      - name: Run Cppcheck
        run: cppcheck --enable=all --inconclusive --report-progress --std=c++17 src/

      - name: Package build
        run: |
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DGENERATE_PKG_CONFIG=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build --clean-first
          cmake --install build --prefix build/pkg/usr/ --strip
          tree -p build/pkg/
          rm -fR build

      - name: Run tests
        run: |
          cmake -S tests -B build
          cmake --build build --clean-first
          ctest -V --test-dir build
          rm -fR build
